### ISSUE TITLE
磁力链接的短链接跳转好像失效了

### ISSUE THREAD

**Issue by imleean** [skywind3000/preserve-cd#32]
求帮忙看看

**Comment by HydrangeaPurple** [comment]
> 求帮忙看看
![Screenshot_2023-11-18-02-31-47-741_com.termux~01.jpg](https://github.com/skywind3000/preserve-cd/assets/21093249/6b9ebf80-1f01-4c27-aeef-74f7c99551f2)



curl看了下，没问题，你通过代理试试

**Comment by imleean** [comment]
网络问题， 感谢大佬~已解决
