### ISSUE TITLE
建议补一个天翼云链接

### ISSUE THREAD

**Issue by Zhangxxl** [skywind3000/preserve-cd#5]
百度云和115没有会员下载实在太慢了，天翼云盘即便是没有会员用网页下单个文件也不会被限速

**Comment by skywind3000** [comment]
我不是电信网络，访问天翼太慢，欢迎提供并 PR。

不过光盘本身很小，每张 650MB，不是那种动辄 50GB 的游戏，即便限速，下载起来也不会太慢。

**Comment by Zhangxxl** [comment]
已PR
