### ISSUE TITLE
关于License选择

### ISSUE THREAD

**Issue by KevinMX** [skywind3000/preserve-cd#8]
发现本仓库使用了CC0作为License，也就是作为公有领域发布，但考虑到各种软件/游戏可能仍有Copyright，似乎不太合适？

**Comment by skywind3000** [comment]
那你说应该用啥？

**Comment by KevinMX** [comment]
这方面我也不是很了解，也许撤掉LICENSE更好（？）

**Comment by skywind3000** [comment]
这个 LICENSE 是针对本仓库里的文件的，即，README.md 之类。

**Comment by KevinMX** [comment]
只是希望稍微注意一下，如果不涉及其他软件，只是本仓库内的内容的话可能还好，毕竟这样的仓库万一被Take Down了也不好啊（
